#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 28, 2020 04:11:50 AM PKT  platform: Windows NT

import sys
import ctypes
import platform



try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import IrisApplication_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    IrisApplication_support.set_Tk_var()
    top = Iris_Classification (root)
    IrisApplication_support.init(root, top)
    root.mainloop()

w = None


def make_dpi_aware():
    if int(platform.release()) >= 8:
        ctypes.windll.shcore.SetProcessDpiAwareness(True)

def create_Iris_Classification(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Iris_Classification(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    IrisApplication_support.set_Tk_var()
    top = Iris_Classification (w)
    IrisApplication_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Iris_Classification():
    global w
    w.destroy()
    w = None

class Iris_Classification:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("820x451+310+196")
        top.minsize(208, 1)
        top.maxsize(1924, 1044)
        top.resizable(0, 0)
        top.title("New Toplevel")
        top.configure(background="#c4dae7")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.254, rely=0.044, height=36, width=401)
        self.Label1.configure(activebackground="#99aad6")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#c4dae7")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''IRIS Classification Application''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.024, rely=0.2, height=36, width=184)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#bbe5ff")
        self.Label2.configure(borderwidth="3")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(relief="raised")
        self.Label2.configure(text='''Sepal Length in cm''')

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.024, rely=0.299, height=36, width=184)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#bbe5ff")
        self.Label2_1.configure(borderwidth="3")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(relief="raised")
        self.Label2_1.configure(text='''Sepal Width in cm''')

        self.Label2_2 = tk.Label(top)
        self.Label2_2.place(relx=0.024, rely=0.399, height=36, width=183)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(anchor='w')
        self.Label2_2.configure(background="#bbe5ff")
        self.Label2_2.configure(borderwidth="3")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(relief="raised")
        self.Label2_2.configure(text='''Petal Length in cm''')

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.024, rely=0.499, height=36, width=183)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(anchor='w')
        self.Label2_1.configure(background="#bbe5ff")
        self.Label2_1.configure(borderwidth="3")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(relief="raised")
        self.Label2_1.configure(text='''Petal Width in cm''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.26, rely=0.2,height=36, relwidth=0.176)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.26, rely=0.299,height=36, relwidth=0.176)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.26, rely=0.399,height=36, relwidth=0.176)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.26, rely=0.499,height=36, relwidth=0.176)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.18, rely=0.621, height=51, width=120)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#9ad9ff")
        self.Button1.configure(borderwidth="3")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Predict''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.024, rely=0.82, height=36, width=183)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#bbe5ff")
        self.Label3.configure(borderwidth="3")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(relief="groove")
        self.Label3.configure(text='''Predicted:''')

        self.Radiobutton1 = tk.Radiobutton(top)
        self.Radiobutton1.place(relx=0.46, rely=0.288, relheight=0.098
                , relwidth=0.09)
        self.Radiobutton1.configure(activebackground="#c4dae7")
        self.Radiobutton1.configure(activeforeground="#c4dae7")
        self.Radiobutton1.configure(anchor='w')
        self.Radiobutton1.configure(background="#c4dae7")
        self.Radiobutton1.configure(command=IrisApplication_support.get_model_val)
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''KNN''')
        self.Radiobutton1.configure(value="1")
        self.Radiobutton1.configure(variable=IrisApplication_support.var)

        self.Radiobutton2 = tk.Radiobutton(top)
        self.Radiobutton2.place(relx=0.46, rely=0.377, relheight=0.098
                , relwidth=0.09)
        self.Radiobutton2.configure(activebackground="#c4dae7")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(anchor='w')
        self.Radiobutton2.configure(background="#c4dae7")
        self.Radiobutton2.configure(command=IrisApplication_support.get_model_val)
        self.Radiobutton2.configure(cursor="fleur")
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''NB''')
        self.Radiobutton2.configure(value="2")
        self.Radiobutton2.configure(variable=IrisApplication_support.var)

        self.Label0_1 = tk.Label(top)
        self.Label0_1.place(relx=0.579, rely=0.2, height=36, width=184)
        self.Label0_1.configure(activebackground="#f9f9f9")
        self.Label0_1.configure(activeforeground="black")
        self.Label0_1.configure(anchor='w')
        self.Label0_1.configure(background="#bbe5ff")
        self.Label0_1.configure(borderwidth="3")
        self.Label0_1.configure(disabledforeground="#a3a3a3")
        self.Label0_1.configure(foreground="#000000")
        self.Label0_1.configure(highlightbackground="#d9d9d9")
        self.Label0_1.configure(highlightcolor="black")
        self.Label0_1.configure(relief="raised")
        self.Label0_1.configure(text='''sepal length in cm''')

        self.Label0_2 = tk.Label(top)
        self.Label0_2.place(relx=0.579, rely=0.299, height=36, width=184)
        self.Label0_2.configure(activebackground="#f9f9f9")
        self.Label0_2.configure(activeforeground="black")
        self.Label0_2.configure(anchor='w')
        self.Label0_2.configure(background="#bbe5ff")
        self.Label0_2.configure(borderwidth="3")
        self.Label0_2.configure(disabledforeground="#a3a3a3")
        self.Label0_2.configure(foreground="#000000")
        self.Label0_2.configure(highlightbackground="#d9d9d9")
        self.Label0_2.configure(highlightcolor="black")
        self.Label0_2.configure(relief="raised")
        self.Label0_2.configure(text='''sepal width in cm''')

        self.Label0_3 = tk.Label(top)
        self.Label0_3.place(relx=0.579, rely=0.399, height=36, width=184)
        self.Label0_3.configure(activebackground="#f9f9f9")
        self.Label0_3.configure(activeforeground="black")
        self.Label0_3.configure(anchor='w')
        self.Label0_3.configure(background="#bbe5ff")
        self.Label0_3.configure(borderwidth="3")
        self.Label0_3.configure(disabledforeground="#a3a3a3")
        self.Label0_3.configure(foreground="#000000")
        self.Label0_3.configure(highlightbackground="#d9d9d9")
        self.Label0_3.configure(highlightcolor="black")
        self.Label0_3.configure(relief="raised")
        self.Label0_3.configure(text='''petal length in cm''')

        self.Label0_4 = tk.Label(top)
        self.Label0_4.place(relx=0.579, rely=0.499, height=36, width=184)
        self.Label0_4.configure(activebackground="#f9f9f9")
        self.Label0_4.configure(activeforeground="black")
        self.Label0_4.configure(anchor='w')
        self.Label0_4.configure(background="#bbe5ff")
        self.Label0_4.configure(borderwidth="3")
        self.Label0_4.configure(disabledforeground="#a3a3a3")
        self.Label0_4.configure(foreground="#000000")
        self.Label0_4.configure(highlightbackground="#d9d9d9")
        self.Label0_4.configure(highlightcolor="black")
        self.Label0_4.configure(relief="raised")
        self.Label0_4.configure(text='''petal width in cm''')

        self.Labelg_1 = tk.Label(top)
        self.Labelg_1.place(relx=0.817, rely=0.2, height=36, width=55)
        self.Labelg_1.configure(activebackground="#f9f9f9")
        self.Labelg_1.configure(activeforeground="black")
        self.Labelg_1.configure(background="#c4dae7")
        self.Labelg_1.configure(disabledforeground="#a3a3a3")
        self.Labelg_1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Labelg_1.configure(foreground="#000000")
        self.Labelg_1.configure(highlightbackground="#d9d9d9")
        self.Labelg_1.configure(highlightcolor="black")
        self.Labelg_1.configure(text='''...''')

        self.Labelg_2 = tk.Label(top)
        self.Labelg_2.place(relx=0.822, rely=0.299, height=36, width=55)
        self.Labelg_2.configure(activebackground="#f9f9f9")
        self.Labelg_2.configure(activeforeground="black")
        self.Labelg_2.configure(background="#c4dae7")
        self.Labelg_2.configure(disabledforeground="#a3a3a3")
        self.Labelg_2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Labelg_2.configure(foreground="#000000")
        self.Labelg_2.configure(highlightbackground="#d9d9d9")
        self.Labelg_2.configure(highlightcolor="black")
        self.Labelg_2.configure(text='''...''')

        self.Labelg_3 = tk.Label(top)
        self.Labelg_3.place(relx=0.822, rely=0.399, height=36, width=55)
        self.Labelg_3.configure(activebackground="#f9f9f9")
        self.Labelg_3.configure(activeforeground="black")
        self.Labelg_3.configure(background="#c4dae7")
        self.Labelg_3.configure(disabledforeground="#a3a3a3")
        self.Labelg_3.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Labelg_3.configure(foreground="#000000")
        self.Labelg_3.configure(highlightbackground="#d9d9d9")
        self.Labelg_3.configure(highlightcolor="black")
        self.Labelg_3.configure(text='''...''')

        self.Labelg_4 = tk.Label(top)
        self.Labelg_4.place(relx=0.822, rely=0.499, height=36, width=55)
        self.Labelg_4.configure(activebackground="#f9f9f9")
        self.Labelg_4.configure(activeforeground="black")
        self.Labelg_4.configure(background="#c4dae7")
        self.Labelg_4.configure(disabledforeground="#a3a3a3")
        self.Labelg_4.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Labelg_4.configure(foreground="#000000")
        self.Labelg_4.configure(highlightbackground="#d9d9d9")
        self.Labelg_4.configure(highlightcolor="black")
        self.Labelg_4.configure(text='''...''')

        self.GenerateSample = tk.Button(top)
        self.GenerateSample.place(relx=0.634, rely=0.621, height=51, width=180)
        self.GenerateSample.configure(activebackground="#ececec")
        self.GenerateSample.configure(activeforeground="#000000")
        self.GenerateSample.configure(background="#9ad9ff")
        self.GenerateSample.configure(borderwidth="3")
        self.GenerateSample.configure(disabledforeground="#a3a3a3")
        self.GenerateSample.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.GenerateSample.configure(foreground="#000000")
        self.GenerateSample.configure(highlightbackground="#d9d9d9")
        self.GenerateSample.configure(highlightcolor="black")
        self.GenerateSample.configure(pady="0")
        self.GenerateSample.configure(text='''Generate Sample''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.26, rely=0.82, height=36, width=144)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#c4dae7")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 9 -weight bold -slant italic")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''-----''')

        self.Label3_2 = tk.Label(top)
        self.Label3_2.place(relx=0.579, rely=0.82, height=36, width=183)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#bbe5ff")
        self.Label3_2.configure(borderwidth="3")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label3_2.configure(foreground="#000000")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(relief="groove")
        self.Label3_2.configure(text='''Actual:''')

        self.Label4_1 = tk.Label(top)
        self.Label4_1.place(relx=0.822, rely=0.82, height=36, width=105)
        self.Label4_1.configure(activebackground="#f9f9f9")
        self.Label4_1.configure(activeforeground="black")
        self.Label4_1.configure(background="#c4dae7")
        self.Label4_1.configure(disabledforeground="#a3a3a3")
        self.Label4_1.configure(font="-family {Segoe UI} -size 9 -weight bold -slant italic")
        self.Label4_1.configure(foreground="#000000")
        self.Label4_1.configure(highlightbackground="#d9d9d9")
        self.Label4_1.configure(highlightcolor="black")
        self.Label4_1.configure(text='''-----''')

if __name__ == '__main__':
    make_dpi_aware()
    vp_start_gui()





